Development
Christonn93/css-frameworks pull request #5
Opened 2022-08-30 10:45 UTC by Christonn93

2022-08-30 10:54 UTC, Fermain requested changes
No major issues, just a few places where you have doubled up on BS

2022-08-30 10:54 UTC, Fermain commented on package.json
> +  "version": "2.0.0",
```suggestion
  "version": "1.0.1",
```
Version numbers go Major.Minor.Patch where major version represents a substantial change

2022-08-30 10:54 UTC, Fermain commented on public/pages/login/index.html
> +    <script src="./node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
```suggestion
```

You should only be linking to your styles. Your file imports bootstrap, so you don't need to duplicate it.

2022-08-30 10:54 UTC, Fermain commented on src/scss/index.scss
> +$theme-main: #08517e;
This should all be in the _variables file

2022-08-30 10:54 UTC, Fermain commented on src/scss/index.scss
> +    border-radius: 0.75rem;
Bootstrap has classes for controlling border-radius

2022-08-30 10:54 UTC, Fermain commented on src/scss/index.scss
> +    justify-content: space-between;
Bootstrap has `.justify-content-between` and `.align-items-center` classes

2022-08-30 10:54 UTC, Fermain commented on src/scss/index.scss
> +  .container-login {
All of these flex styles can be set with classes

2022-08-30 10:54 UTC, Fermain commented on src/scss/index.scss
> +  .hidden {
Bootstrap has `.d-none`

2022-08-30 10:58 UTC, Christonn93 commented on public/pages/login/index.html
> +    <script src="./node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
If i remove this, the collapse menu for navigation cant work.

2022-08-30 11:00 UTC, Fermain commented on public/pages/login/index.html
> +    <script src="./node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
You are right, my mistake.

2022-08-30 11:02 UTC, Christonn93 commented on src/scss/index.scss
> +    justify-content: space-between;
This and all the classes under is removed, it have not been used in the code, it was part of my layout planning before I changed all to use bootstrap classes.

2022-08-30 11:04 UTC, Christonn93 commented on src/scss/index.scss
> +  .hidden {
Thanks.  Did not know that so I will use that class if i need to hide something. 

It was ment for hiding link to profile until you are logged in. But skipped it for now and plan to add something like that in js later on but don't know how it would work without a back end server running to make sure the user info match up to unlock the profile page.

2022-08-30 11:12 UTC, Christonn93 commented on src/scss/index.scss
> +$theme-main: #08517e;
![image](https://user-images.githubusercontent.com/46559129/187422055-ada1cebe-43c4-49e3-a0cc-ddd0c295e888.png)
Need to add both of them in variable file to make the colors show up. 

Does not look right in my head that i need to import bootstrap in  `Index.scss` and inside `_variables.scss` also.

2022-08-30 11:13 UTC, Christonn93 commented on src/scss/index.scss
> +    border-radius: 0.75rem;
I will look into that.

2022-08-30 11:23 UTC, Fermain commented on src/scss/index.scss
> +$theme-main: #08517e;
You can add them in variables and remove them here. So it goes:

`index.scss`
```scss
@import "variables";
@import "path/to/bootstrap";
```

Then in _variables you have:

```scss
$your-overrides here

@import "bootstrap/functions"
@import "bootstrap/mixins"
@import "bootstrap/variables"

$your map-merges-here
```

Not 100% sure about the ordering of the imports

2022-08-30 11:31 UTC, Christonn93 commented on src/scss/index.scss
> +$theme-main: #08517e;
![image](https://user-images.githubusercontent.com/46559129/187425076-11a03de2-6803-4bda-83e9-8df089d9f45c.png)

All style is working now when including inside `_variables.scss`
`
@import "../../../node_modules/bootstrap/scss/bootstrap";
@import "../../../node_modules/bootstrap/scss/functions";
`

As soon as i remove `@import "../../../node_modules/bootstrap/scss/bootstrap";`
This happens
![image](https://user-images.githubusercontent.com/46559129/187425338-0eda08fd-93ae-4fc9-806a-b56530fe049d.png)


If i add all the imports you list nothing changes 
![image](https://user-images.githubusercontent.com/46559129/187425673-a5562255-bb63-4dfe-8859-2c5d689df6b5.png)


And by adding the map-merge at the bottom still no changes 
![image](https://user-images.githubusercontent.com/46559129/187425817-c87372c4-5df5-4078-81a4-4d46d055d114.png)


Thats why i had all of them in the `index.scss` file..

2022-08-30 19:38 UTC, Christonn93 commented on src/scss/index.scss
> +$theme-main: #08517e;
So i dont know what to do to resolve this.

2022-08-31 04:14 UTC, sulenchy commented on .gitignore
> +testing/
A new line is required here

2022-08-31 04:28 UTC, sulenchy commented on package.json
> +    "build": "sass src/scss:public/style/css",
Why do you choose to dump the generated CSS in the public folder? I can see in the course content that the generated CSS files are being kept in a dist folder. The public folder is not meant to keep generated code but rather static files such as fonts, images, etc. The dist folder is meant to keep generated code and is not meant to be pushed to GitHub. In fact, you have a dist folder included in you .gitignore file already.

2022-08-31 04:30 UTC, sulenchy commented
@Christonn93 I think the pages folder should either be in the src folder or be on its own. The public folder is meant to keep only static files such as images, files, etc.

2022-08-31 04:35 UTC, sulenchy commented
Also, this PR should have a description. Currently, you have no description. You can look up how to add PR template at [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

2022-08-31 05:19 UTC, Christonn93 commented on package.json
> +    "build": "sass src/scss:public/style/css",
Why i choose to have the style in public is because when the site is built, the style sheet is static. After the build of the site when its 100% complete the style don't change unless you make a change and rebuild the scss. 

This is for me just about how i name the folders, I have requested to have a introduction to what the industry does when naming the folders and files, because now, I believe everyone does it in there own way. 

So i would greatly appreciate if someone could make a list, over the industry standard of naming folders, and why the naming is like it is. 
For me this is important, not only for consistency but also for the future work.

2022-08-31 05:20 UTC, Christonn93 commented on .gitignore
> +testing/
Please, explain what you mean with this. 
Thanks

2022-08-31 05:22 UTC, Christonn93 commented on src/scss/index.scss
> +$theme-main: #08517e;
@Fermain @sulenchy 

This one is a struggle for me to get right. Would be grateful to get some guidance to get it working right,.

2022-09-01 06:25 UTC, merged